### ISSUE TITLE
May I ask how to obtain the bin file for tokenizer? Thank you

### ISSUE THREAD

**Issue by zsg0827** [iangitonga/nanochatllms.cpp#1]

**Comment by iangitonga** [comment]
Hello, apologies for the delayed response. 

For the MiniCPM and TinyLLama models, I used the script [HERE](https://github.com/karpathy/llama2.c/blob/master/tokenizer.py) to create them.

And as for the Zephyr model, I used the bin data for the GPT2 tokenizer obtained from [HERE](https://github.com/ggerganov/ggml/tree/master/examples/gpt-2). The bin data is embedded in the model files.
